GEARPLUG/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('apps.urls', 'apps'), namespace="apps")),
]

apps/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from django_filters.views import object_filter
from .models import *
from django_filters.views import FilterView
from .views import *
urlpatterns = [
    path("", list_url.as_view(), name="index"),
    #listar
    path("list/personajes", FilterView.as_view(model=personaje), name="personajes-list"),
    path("list/peliculas", FilterView.as_view(model=pelicula), name="peliculas-list"),
    path("list/planetas", FilterView.as_view(model=planeta), name="planetas-list"),
    #Crear
    path("add/personajes", login_required(add_personaje.as_view()), name="personajes-add"),
    #path("add/peliculas", add_pelicula.as_view(), name="product-add"),
    #path("add/planetas", add_planeta.as_view(), name="product-list"),
]

apps/models.py
from distutils import text_file
from django.db import models
from django.forms import CharField
import django_filters

# Create your models here.
class planeta(models.Model):
    nombre = models.CharField(max_length=100)
    def __str__(self):
        return '{}'.format(self.nombre)

class pelicula(models.Model):
    titulo = models.CharField(max_length=100)
    texto_apertura = models.TextField()
    director = models.CharField(max_length=100)
    productor = models.CharField(max_length=100)
    planetas = models.ManyToManyField(planeta)
    def __str__(self):
        return '{}'.format(self.titulo)

class personaje(models.Model):    
    nombre = models.CharField(max_length=50)
    altura = models.IntegerField()
    masa = models.IntegerField()
    color_pelo = models.CharField(max_length=50)
    color_piel = models.CharField(max_length=50)
    color_ojos = models.CharField(max_length=50)
    año_nacimiento = models.IntegerField()
    genero = models.CharField(max_length=50)
    mundo_natal = models.ForeignKey(planeta, verbose_name=("mundo_natal"), on_delete=models.CASCADE)
    peliculas_participa = models.ManyToManyField(pelicula, verbose_name=("peliculas"))
    def __str__(self):
        return '{}'.format(self.nombre)
class personajeFilter(django_filters.FilterSet):
    nombre = django_filters.CharFilter(lookup_expr='icontains')

    class Meta:
        model = personaje
        fields = ['nombre', ]

apps/forms.py
from django import forms
from .models import *

class personajeForm(forms.ModelForm):
	class Meta:
		model = personaje
		fields = '__all__'
	def __init__(self, *args, **kwargs):
		super(personajeForm, self).__init__(*args, **kwargs)
		for visible in self.visible_fields():
			visible.field.widget.attrs['class'] = 'form-control'

class peliculaForm(forms.ModelForm):
	class Meta:
		model = pelicula
		fields = '__all__'

	def __init__(self, *args, **kwargs):
		super(peliculaForm, self).__init__(*args, **kwargs)
		for visible in self.visible_fields():
			visible.field.widget.attrs['class'] = 'form-control'

class planetaForm(forms.ModelForm):
	class Meta:
		model = planeta
		fields = '__all__'

	def __init__(self, *args, **kwargs):
		print(kwargs.pop('request'))
		super(planetaForm, self).__init__(*args, **kwargs)
		for visible in self.visible_fields():
			visible.field.widget.attrs['class'] = 'form-control'

apps/views.py
from django.shortcuts import render
from .forms import *
from django.views.generic.edit import FormView,CreateView
from django.views.generic import TemplateView
from django.urls import reverse_lazy
# Create your views here.
class add_personaje(CreateView):
    model = personaje
    form_class = personajeForm
    template_name = 'apps/add_personaje.html'
    success_url = reverse_lazy('apps:index')



class list_url(TemplateView):
    template_name = "apps/list_url.html"

templates/apps/add_personaje.html
{% extends "layouts/master.html" %}

{% block content %}
    <div class="row d-flex justify-content-center m-2">
        <form method="post">{% csrf_token %}
            {{ form.as_p }}
            <input type="submit" />
        </form>
    </div>
{% endblock %}

templates/apps/list_url.html
<ul>
    <li><a href="{% url 'apps:index' %}">Index</a></li>
    <li><a href="{% url 'apps:personajes-list' %}">Personajes</a></li>
    <li><a href="{% url 'apps:peliculas-list' %}">Peliculas</a></li>
    <li><a href="{% url 'apps:planetas-list' %}">Planetas</a></li>
    <li><a href="{% url 'apps:personajes-add' %}">Añadir Personaje</a></li>
</ul>

templates/apps/pelicula_filter.html
{% extends "layouts/master.html" %}

{% block content %}
    <div class="row d-flex justify-content-center m-2">
        <form method="get">
            {{ filter.form.titulo }}
            <input type="submit" />
        </form>
    </div>
    <div class="row  d-flex justify-content-center m-2 border-bottom">
        {% for obj in filter.qs %}
            titulo : {{obj.titulo}}<br>
            texto_apertura : {{obj.texto_apertura|safe}}<br>
            director : {{obj.director}}<br>
            productor : {{obj.productor}}<br>
            planetas : {{obj.planetas.all|join:", "}}<br>
        {% endfor %}
</div>
{% endblock %}

templates/apps/personaje_filter.html
{% extends "layouts/master.html" %}

{% block content %}
    <div class="row d-flex justify-content-center m-2">
        <form method="get">
            {{ filter.form.nombre }}
            <input type="submit" />
        </form>
    </div>
    <div class="row  d-flex justify-content-center m-2 border-bottom">
        {% for obj in filter.qs %}
            nombre : {{obj.nombre}} <br>
            altura : {{obj.altura}} <br>
            masa : {{obj.masa}} <br>
            color_pelo : {{obj.color_pelo}} <br>
            color_piel : {{obj.color_piel}} <br>
            color_ojos : {{obj.color_ojos}} <br>
            año_nacimiento : {{obj.año_nacimiento}} <br>
            género : {{obj.genero}} <br>
            mundo_natal : {{obj.mundo_natal}} <br>
            peliculas_participa : {{obj.peliculas_participa.all|join:", "}} <br>
        
        {% endfor %}
</div>
{% endblock %}

templates/apps/planeta_filter.html
{% extends "layouts/master.html" %}

{% block content %}
    <div class="row d-flex justify-content-center m-2">
        <form method="get">
            {{ filter.form.nombre }}
            <input type="submit" />
        </form>
    </div>
    <div class="row  d-flex justify-content-center m-2">
        {% for obj in filter.qs %}
            nombre : {{obj.nombre}} <br>       
        {% endfor %}
</div>
{% endblock %}

templates/layouts/master.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
  </head>
  <body class="body">
	    {% block content %}{% endblock %}
  </body
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>